sudo: required
services:
        - docker
before_install:
        - docker build -t xneyder/docker-react -f Dockerfile.dev .

script:
        - docker run xneyder/docker-react npm run test -- --coverage
